from PyQt5 import QtCore ,QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self,MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1870,1000)
        MainWindow.setMinimumSize(QtCore.QSize(1870, 1000))
        MainWindow.setMaximumSize(QtCore.QSize(1870, 1000))
        # MainWindow.setStyleSheet("border-image:url(G:/PCBDetection/UIProgram/ui_imgs/background_noword.png)")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/ui_imgs/icons/目标检测.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # 添加图标
        MainWindow.setWindowIcon(icon)
        
        # 创建主控件
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        # 创建模块一
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 890, 800))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        
        # 创建“目标位置”模块
        
        self.frame_object = QtWidgets.QFrame(self.frame)
        self.frame_object.setGeometry(QtCore.QRect(80, 0, 483, 394))
        self.frame_object.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_object.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_object.setObjectName("frame_object")
        
        self.lable_4 = QtWidgets.QLabel(self.frame_object)
        self.lable_4.setGeometry(QtCore.QRect(10,10,131,41))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        self.lable_4.setObjectName("label_4")
        
        # xmin
        self.layoutWidget = QtWidgets.QWidget(self.frame_object)  
        self.layoutWidget.setGeometry(QtCore.QRect(20, 200, 161, 37))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")    
        self.lable_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.lable_6.setFont(font)
        self.lable_6.setObjectName("lable_6")
        self.horizontalLayout.addWidget(self.lable_6)
        self.label_xmin = QtWidgets.QLabel(self.layoutWidget)
        
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_xmin.setPalette(palette)
        self.label_xmin.setText("")
        self.label_xmin.setObjectName("label_xmin")
        self.horizontalLayout.addWidget(self.label_xmin)
        
        # ymin
        self.layoutWidget1 = QtWidgets.QWidget(self.frame_object)
        self.layoutWidget1.setGeometry(210, 60, 161, 37)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0,0,0,0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.label_ymin = QtWidgets.QLabel(self.layoutWidget1)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_ymin.setPalette(palette)
        self.label_ymin.setText("")
        self.label_ymin.setObjectName("label_ymin")
        self.horizontalLayout_2.addWidget(self.label_ymin)
        
        
        # xmax
        self.layoutWidget2 = QtWidgets.QWidget(self.frame_object)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 120, 161, 37))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.label_xmax = QtWidgets.QLabel(self.layoutWidget2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_xmax.setPalette(palette)
        self.label_xmax.setText("")
        self.label_xmax.setObjectName("label_xmax")
        self.horizontalLayout_3.addWidget(self.label_xmax)
        
        # ymax
        self.layoutWidget3 = QtWidgets.QWidget(self.frame_object)
        self.layoutWidget3.setGeometry(QtCore.QRect(210, 120, 161, 37))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.label_ymax = QtWidgets.QLabel(self.layoutWidget3)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_ymax.setPalette(palette)
        self.label_ymax.setText("")
        self.label_ymax.setObjectName("label_ymax")
        self.horizontalLayout_4.addWidget(self.label_ymax)

        
        
        # 创建“检测结果”模块
        
        # self.groupBox_2 = QtWidgets.QGroupBox(self.frame_result)
        # self.groupBox_2.setGeometry(QtCore.QRect(0, 180, 431, 371))
        # font = QtGui.QFont()
        # font.setFamily("华文楷体")
        # font.setPointSize(16)
        # self.groupBox_2.setFont(font)
        # self.groupBox_2.setObjectName("groupBox_2")
        
        self.frame_result = QtWidgets.QFrame(self.frame)
        self.frame_result.setGeometry(QtCore.QRect(20, 500, 600, 500))
        self.frame_result.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_result.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_result.setObjectName("frame_result")
        # 添加暂停模块
        self.stopBtn = QtWidgets.QPushButton(self.frame_result)
        self.stopBtn.setGeometry(QtCore.QRect(485, 200, 30, 29))
        self.stopBtn.setText("暂停")
        self.stopBtn.setObjectName("stopBtn")
        
        # 添加检测结果模块
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_result)
        self.groupBox_2.setGeometry(QtCore.QRect(70, 60, 483, 500))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        
        self.layoutWidget4 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget4.setGeometry(QtCore.QRect(208, 40, 211, 37))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.layoutWidget4)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.label_nums = QtWidgets.QLabel(self.layoutWidget4)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.label_nums.setPalette(palette)
        self.label_nums.setText("")
        self.label_nums.setObjectName("label_nums")
        self.horizontalLayout_5.addWidget(self.label_nums)
        
        
        self.layoutWidget5 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 80, 291, 38))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget5)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_6.addWidget(self.comboBox)
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 50, 171, 37))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        self.time_lb = QtWidgets.QLabel(self.layoutWidget_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.time_lb.setPalette(palette)
        self.time_lb.setText("")
        self.time_lb.setObjectName("time_lb")
        self.horizontalLayout_7.addWidget(self.time_lb)
        
        self.layoutWidget6 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget6.setGeometry(QtCore.QRect(10, 120, 191, 41))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_8.addWidget(self.label_11)
        self.label_conf = QtWidgets.QLabel(self.layoutWidget6)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_conf.setPalette(palette)
        self.label_conf.setText("")
        self.label_conf.setObjectName("label_conf")
        self.horizontalLayout_8.addWidget(self.label_conf)
        
        
        
        
        
        self.frame_6 = QtWidgets.QFrame(self.frame_object)
        self.frame_6.setGeometry(QtCore.QRect(0, 200, 431, 171))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_4 = QtWidgets.QLabel(self.frame_6)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 131, 41))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("")
        self.label_4.setObjectName("label_4")
        
        
        self.layoutWidget = QtWidgets.QWidget(self.frame_6)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 60, 161, 37))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        
        
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.label_xmin = QtWidgets.QLabel(self.layoutWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_xmin.setPalette(palette)
        self.label_xmin.setText("")
        self.label_xmin.setObjectName("label_xmin")
        self.horizontalLayout.addWidget(self.label_xmin)
        self.layoutWidget1 = QtWidgets.QWidget(self.frame_6)
        self.layoutWidget1.setGeometry(QtCore.QRect(210, 60, 161, 37))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.label_ymin = QtWidgets.QLabel(self.layoutWidget1)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_ymin.setPalette(palette)
        self.label_ymin.setText("")
        self.label_ymin.setObjectName("label_ymin")
        self.horizontalLayout_2.addWidget(self.label_ymin)
        self.layoutWidget2 = QtWidgets.QWidget(self.frame_6)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 120, 161, 37))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.label_xmax = QtWidgets.QLabel(self.layoutWidget2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_xmax.setPalette(palette)
        self.label_xmax.setText("")
        self.label_xmax.setObjectName("label_xmax")
        self.horizontalLayout_3.addWidget(self.label_xmax)
        self.layoutWidget3 = QtWidgets.QWidget(self.frame_6)
        self.layoutWidget3.setGeometry(QtCore.QRect(210, 120, 161, 37))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.label_ymax = QtWidgets.QLabel(self.layoutWidget3)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_ymax.setPalette(palette)
        self.label_ymax.setText("")
        self.label_ymax.setObjectName("label_ymax")
        self.horizontalLayout_4.addWidget(self.label_ymax)
        
        
        self.layoutWidget4 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget4.setGeometry(QtCore.QRect(208, 40, 211, 37))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.layoutWidget4)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.label_nums = QtWidgets.QLabel(self.layoutWidget4)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.label_nums.setPalette(palette)
        self.label_nums.setText("")
        self.label_nums.setObjectName("label_nums")
        self.horizontalLayout_5.addWidget(self.label_nums)
        
        self.layoutWidget5 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 90, 291, 38))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget5)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_6.addWidget(self.comboBox)
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 40, 171, 37))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        self.time_lb = QtWidgets.QLabel(self.layoutWidget_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.time_lb.setPalette(palette)
        self.time_lb.setText("")
        self.time_lb.setObjectName("time_lb")
        self.horizontalLayout_7.addWidget(self.time_lb)
        
        self.layoutWidget6 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget6.setGeometry(QtCore.QRect(10, 140, 191, 41))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_8.addWidget(self.label_11)
        self.label_conf = QtWidgets.QLabel(self.layoutWidget6)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_conf.setPalette(palette)
        self.label_conf.setText("")
        self.label_conf.setObjectName("label_conf")
        self.horizontalLayout_8.addWidget(self.label_conf)
        
        
        
        # 创建模块二
        
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(500, 185, 966, 890))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        
        # 创建“图片”模块
        self.frame_label = QtWidgets.QFrame(self.frame_2)
        self.frame_label.setGeometry(QtCore.QRect(60, 0, 966, 394))
        self.frame_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_label.setObjectName("frame_label")
        
        # 添加图片
        self.label_show = QtWidgets.QLabel(self.frame_label)
        self.label_show.setGeometry(QtCore.QRect(0, 0, 750, 330))
        self.label_show.setMinimumSize(QtCore.QSize(750, 330))
        self.label_show.setMaximumSize(QtCore.QSize(750, 330))
        pixmap = QtGui.QPixmap("G:/PCBDetection/UIProgram/ui_imgs/chack.png")
        self.label_show.setScaledContents(True)

        # 设置标签的图片
        self.label_show.setPixmap(pixmap)

        # 设置样式表
        # self.label_show.setStyleSheet("background-color: rgba(0, 0, 0, 0);")

        op = QtWidgets.QGraphicsOpacityEffect()
        op.setOpacity(0.7)
        self.label_show.setGraphicsEffect(op)
        self.label_show.setAutoFillBackground(True)
        self.label_show.setText("")
        self.label_show.setObjectName("label_show")
        
        
        # 创建“表格”模块
        
        self.frame_table = QtWidgets.QFrame(self.frame_2)
        self.frame_table.setGeometry(QtCore.QRect(0,585 ,890 , 180))
        self.frame_table.setObjectName("frame_table")
        
        # 添加表格
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame_table)
        self.groupBox_3.setGeometry(QtCore.QRect(0,10,890,221))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        
        # 添加栏位
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_3)
        self.tableWidget.setGeometry(QtCore.QRect(30,27,890, 221))
        self.tableWidget.setStyleSheet("background-color: transparent; border: none;")
        self.tableWidget.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.tableWidget.verticalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)



        font.setFamily("华文楷体")
        font.setPointSize(14)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setStyleSheet("color: rgb(33,207, 223)")
        self.tableWidget.verticalHeader().setStyleSheet("color: rgb(33,207, 223); ")
        item = QtWidgets.QTableWidgetItem()
        item.setForeground(QtGui.QColor(0, 0, 0))
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setForeground(QtGui.QColor(0, 0, 0))
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setForeground(QtGui.QColor(0, 0, 0))
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setForeground(QtGui.QColor(0, 0, 0))
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setForeground(QtGui.QColor(0, 0, 0))
        self.tableWidget.setHorizontalHeaderItem(4, item)
        
        
        # 创建模块三
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(1410, 185, 471, 890))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        
        
        # 创建“文件”模块
        self.frame_file = QtWidgets.QFrame(self.frame_3)
        self.frame_file.setGeometry(QtCore.QRect(0, 0, 471, 890))
        self.frame_file.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_file.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_file.setObjectName("frame_file")
        
        # 添加文件操作
        self.groupBox = QtWidgets.QGroupBox(self.frame_file)
        self.groupBox.setGeometry(QtCore.QRect(20, 30,471, 300))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(20)
        self.groupBox.setFont(font)
        # 添加文件路径输入框
        self.PiclineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.PiclineEdit.setGeometry(QtCore.QRect(70, 45, 250, 20))
        self.PiclineEdit.setStyleSheet("background-color: transparent; border: none;  color: rgb(33,207, 223)")
        self.PiclineEdit.setInputMask("")
        self.PiclineEdit.setObjectName("PiclineEdit")
        
        self.VideolineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.VideolineEdit.setGeometry(QtCore.QRect(70, 85, 270, 20))
        self.VideolineEdit.setStyleSheet("background-color: transparent; border: none;  color: rgb(33,207, 223)")
        self.VideolineEdit.setObjectName("VideolineEdit")
        
        self.CapBtn = QtWidgets.QPushButton(self.groupBox)
        self.CapBtn.setGeometry(QtCore.QRect(30, 120, 30, 29))
        self.CapBtn.setStyleSheet("border-image: url(UIProgram/ui_imgs/icons/camera.png);")
        self.CapBtn.setText("")
        self.CapBtn.setObjectName("CapBtn")
        
        
        self.PicBtn = QtWidgets.QPushButton(self.groupBox)
        self.PicBtn.setGeometry(QtCore.QRect(30, 40, 30, 29))
        self.PicBtn.setStyleSheet("border-image: url(UIProgram/ui_imgs/icons/img.png);")
        self.PicBtn.setText("")
        self.PicBtn.setObjectName("PicBtn")
        
        
        self.VideoBtn = QtWidgets.QPushButton(self.groupBox)
        self.VideoBtn.setGeometry(QtCore.QRect(30, 80, 30, 29))
        self.VideoBtn.setStyleSheet("border-image: url(UIProgram/ui_imgs/icons/video.png);")
        self.VideoBtn.setText("")
        self.VideoBtn.setObjectName("VideoBtn")

        # 权重
        self.WightBtn = QtWidgets.QPushButton(self.groupBox)
        self.WightBtn.setGeometry(QtCore.QRect(30, 230, 30, 29))
        self.WightBtn.setStyleSheet("border-image: url(UIProgram/ui_imgs/icons/video.png)")
        self.WightBtn.setText("")
        self.WightBtn.setObjectName("WightBtn")
        
        self.WightlineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.WightlineEdit.setGeometry(QtCore.QRect(70, 230, 250, 29))
        self.WightlineEdit.setStyleSheet("background-color: transparent; border: none;  color: rgb(33,207, 223)")
        self.WightlineEdit.setObjectName("WightlineEdit")
        
        
        self.CaplineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.CaplineEdit.setGeometry(QtCore.QRect(70, 125, 270, 20))
        self.CaplineEdit.setStyleSheet("background-color: transparent; border: none;  color: rgb(33,207, 223)")
        self.CaplineEdit.setObjectName("CaplineEdit")
        
        
        self.FilesBtn = QtWidgets.QPushButton(self.groupBox)
        self.FilesBtn.setGeometry(QtCore.QRect(330, 40, 30, 29))
        self.FilesBtn.setStyleSheet("border-image: url(UIProgram/ui_imgs/icons/floder1.png);")
        self.FilesBtn.setText("")
        self.FilesBtn.setObjectName("FilesBtn")
        
        #self.FilesBtn_1 = QtWidgets.QPushButton(self.groupBox)
        #self.FilesBtn_1.setGeometry(QtCore.QRect(330, 230, 30, 29))
        #self.FilesBtn_1.setStyleSheet("border-image: url(UIProgram/ui_imgs/icons/floder1.png);")
        #self.FilesBtn_1.setText("")
        #self.FilesBtn_1.setObjectName("FilesBtn")
        
        
        
        
        
        
        
        # 创建“操作”模块
        self.frame_action = QtWidgets.QFrame(self.frame_3)
        self.frame_action = QtWidgets.QFrame(self.centralwidget)
        self.frame_action.setGeometry(QtCore.QRect(0, 395, 483, 225))
        self.frame_action.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_action.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_action.setObjectName("frame_action")
        
        
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame_file)
        self.groupBox_4.setGeometry(QtCore.QRect(25, 376, 431, 141))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(20)
        font_1 = QtGui.QFont()
        font_1.setFamily("华文楷体")
        font_1.setPointSize(18)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.SaveBtn = QtWidgets.QPushButton(self.groupBox_4)
        self.SaveBtn.setGeometry(QtCore.QRect(0, 59, 153, 51))
        self.SaveBtn.setFont(font_1)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("UIProgram/ui_imgs/icons/保存.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SaveBtn.setIcon(icon1)
        self.SaveBtn.setIconSize(QtCore.QSize(30, 30))
        self.SaveBtn.setObjectName("SaveBtn")
        self.ExitBtn = QtWidgets.QPushButton(self.groupBox_4)
        self.ExitBtn.setGeometry(QtCore.QRect(225, 59, 153, 51))
        self.ExitBtn.setFont(font_1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("UIProgram/ui_imgs/icons/退出.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ExitBtn.setIcon(icon2)
        self.ExitBtn.setIconSize(QtCore.QSize(30, 30))
        self.ExitBtn.setObjectName("ExitBtn")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(150, 10, 1231, 91))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_3 = QtWidgets.QLabel(self.frame_5)
        self.label_3.setGeometry(QtCore.QRect(600, 20, 741, 51))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 311, 21))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(14)
        font.setUnderline(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_12 = QtWidgets.QLabel(self.frame_5)
        self.label_12.setGeometry(QtCore.QRect(1070, 60, 131, 21))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(14)
        font.setUnderline(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")

        
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        
        
    def retranslateUi(self, MainWindow):
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(14)
        self.groupBox.setFont(font)
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "基于YOLOv8深度学习的PCB板缺陷检测系统"))
        self.groupBox_3.setTitle(_translate("MainWindow", "检测结果与位置信息"))
        self.groupBox_3.setStyleSheet("QGroupBox { border: none; } QGroupBox::title { subcontrol-origin: margin; subcontrol-position: top left; padding: 0 40px;color: rgb(33,207, 223) }")
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "序号"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "文件路径"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "类别"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "置信度"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "坐标位置"))
        self.label_xmin.setFont(font)
        self.label_ymin.setFont(font)
        self.label_xmax.setFont(font)
        self.label_ymax.setFont(font)
        self.time_lb.setFont(font)
        self.label_nums.setFont(font)
        self.label_conf.setFont(font)
        self.groupBox.setTitle(_translate("MainWindow", "文件导入"))
        self.groupBox.setStyleSheet("QGroupBox { border: none; } QGroupBox::title { subcontrol-origin: margin; subcontrol-position: top left; padding: 0 40px; color: rgb(33,207, 223)}")
        self.PiclineEdit.setPlaceholderText(_translate("MainWindow", "请选择图片文件"))
        self.VideolineEdit.setPlaceholderText(_translate("MainWindow", "请选择视频文件"))
        self.CaplineEdit.setPlaceholderText(_translate("MainWindow", "摄像头未开启"))
        self.WightlineEdit.setPlaceholderText(_translate("MainWindow", "选择权重文件"))
        self.groupBox_2.setTitle(_translate("MainWindow", "检测结果"))
        self.groupBox_2.setStyleSheet("QGroupBox { border: none; } QGroupBox::title { subcontrol-origin: margin; subcontrol-position: top left; padding: 0 20px;color: rgb(33,207, 223) }")
        self.label_4.setText(_translate("MainWindow", "目标位置："))
        self.label_4.setStyleSheet("color: rgb(33,207, 223)")
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">xmin:</span></p></body></html>"))
        self.label_6.setStyleSheet("color: rgb(33,207, 223)")
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">ymin：</span></p></body></html>"))
        self.label_8.setStyleSheet("color: rgb(33,207, 223)")
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">xmax：</span></p></body></html>"))
        self.label_7.setStyleSheet("color: rgb(33,207, 223)")
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">ymax：</span></p></body></html>"))
        self.label_9.setStyleSheet("color: rgb(33,207, 223)")
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">目标数目：</span></p></body></html>"))
        self.label.setStyleSheet("color: rgb(33,207, 223)")
        self.label.setFont(font)
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">目标选择：</span></p></body></html>"))
        self.label_5.setStyleSheet("color: rgb(33,207, 223)")
        self.label_5.setFont(font)
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">用时：</span></p></body></html>"))
        self.label_10.setStyleSheet("color: rgb(33,207, 223)")
        self.label_10.setFont(font)
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">置信度：</span></p></body></html>"))
        self.label_11.setStyleSheet("color: rgb(33,207, 223)")
        self.label_11.setFont(font)
        self.groupBox_4.setTitle(_translate("MainWindow", "操作"))
        self.groupBox_4.setStyleSheet("QGroupBox { border: none; } QGroupBox::title { subcontrol-origin: margin; subcontrol-position: top left; padding: 0 40px;color: rgb(33,207, 223) }")
        self.SaveBtn.setStyleSheet("color: rgb(33,207, 223)")
        self.ExitBtn.setStyleSheet("color: rgb(33,207, 223)")
        self.SaveBtn.setText(_translate("MainWindow", "保存"))
        self.ExitBtn.setText(_translate("MainWindow", "退出"))
        self.label_3.setText(_translate("MainWindow", "基于YOLOv8的PCB板缺陷检测系统"))
        self.label_3.setStyleSheet("color: white; font-weight: bold;font-size: 25px;")
        # self.label_2.setText(_translate("MainWindow", "公众号：阿旭算法与机器学习"))
        # self.label_12.setText(_translate("MainWindow", "作者：阿旭"))
import ui_sources_rc

        
        
        
